auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: worgold'blog
url: http://worgold.github.io
feed: /atom.xml
author_info: <a href="http://worgold.github.io">worgold</a>
